//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Key]
        public int StudentId { get; set; }

        [Required]
        [Display(Name = "Full Name")]
        public string FullName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Dt. Of Birth")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfBirth { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone No.")]
        public string PhoneNumber { get; set; }

        [Required]
        [Range(0, 10)]
        public double Mathematics { get; set; }

        [Required]
        [Range(0, 10)]
        public double Literatures { get; set; }

        [Required]
        [Range(0, 10)]
        public double English { get; set; }

        [Display(Name ="Avg. Score")]
        public double Average
        {
            get
            {
                return (Mathematics + Literatures + English) / 3;
            }
        }

    }
}
